/*
 * ASee.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.io.IOException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.model.*;
import com.server.Client;
import com.usejdbc.Database;

/**
 * 
 * @author __USER__
 */
public class UControl extends javax.swing.JFrame {

	/** Creates new form ASee */
	public UControl() {
		initComponents();
		try {
			loadTable();
		} catch (UnknownHostException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}

	ArrayList<User> users;
	private final List<String> TITLES2 = Arrays.asList("u_id", "u_fname",
			"u_tname", "u_iden", "u_pw", "u_mail", "u_phone", "u_power");

	void loadTable() throws UnknownHostException, IOException,
			ClassNotFoundException {
		User u = new User();
		users = u.viewData();
		Object title[] = { "用户id", "用户名", "真实姓名", "身份证", "密码", "邮箱", "手机", "权限" };
		Object[][] detail = new Object[users.size()][8];
		for (int i = 0; i < users.size(); i++) {
			detail[i][0] = users.get(i).getU_id();
			detail[i][1] = users.get(i).getU_fname();
			detail[i][2] = users.get(i).getU_tname();
			detail[i][3] = users.get(i).getU_iden();
			detail[i][4] = users.get(i).getU_pw();
			detail[i][5] = users.get(i).getU_mail();
			detail[i][6] = users.get(i).getU_phone();
			detail[i][7] = users.get(i).getU_power();
		}
		this.jTable1.setModel(new DefaultTableModel(detail, title));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u66f4\u6539");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u5220\u9664");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u589e\u52a0");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("\u8fd4\u56de");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u7528\u6237\u7ba1\u7406");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(59, 59,
										59).addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										586,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(86, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(205, Short.MAX_VALUE)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton5).addGap(175,
												175, 175)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										341, Short.MAX_VALUE).addComponent(
										jLabel1).addGap(294, 294, 294)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(35, 35, 35).addComponent(
						jLabel1).addGap(40, 40, 40).addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1).addComponent(jButton2)
								.addComponent(jButton3).addComponent(jButton4)
								.addComponent(jButton5)).addGap(35, 35, 35)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 312,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(31, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		MasterView mv = new MasterView();
		mv.setVisible(true);
		this.dispose();
	}

	// +
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		UCinsert ui = new UCinsert();
		ui.setVisible(true);
	}

	// -
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int row = jTable1.getSelectedRow();
		int sid = users.get(row).getU_id();

		try {
			Client c = new Client();
			User u = c.DeletaUser(sid);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

		JOptionPane.showMessageDialog(null, "删除成功", "提示",
				JOptionPane.PLAIN_MESSAGE);
		users.remove(row);
		// 更新表格
		jTable1.validate();
		jTable1.updateUI();
	}

	// ~
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int row = jTable1.getSelectedRow();
		int column = jTable1.getSelectedColumn();
		if (row == -1 || column == 0)
			return;

		String change = (String) jTable1.getValueAt(row, column);
		int uid = users.get(row).getU_id();
		String select = TITLES2.get(column);
		try {
			Client c = new Client();
			User u = c.UpdateUser(select, uid, change);
		} catch (UnknownHostException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

		JOptionPane.showMessageDialog(null, "更改成功", "提示",
				JOptionPane.PLAIN_MESSAGE);

	}

	// s
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UControl().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}