/*
 * PControl.java
 *
 * Created on __DATE__, __TIME__
 */

package vrew;

import java.io.IOException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import view.CompanyView;
import view.PCinsert;

import com.model.Plane;
import com.server.Client;

/**
 *
 * @author  __USER__
 */
public class PControl extends javax.swing.JFrame {

	ArrayList<Plane> planes;
	private final List<String> TITLES2 = Arrays
			.asList("p_id", "f_id", "p_comp");

	void loadTable() throws UnknownHostException, IOException,
			ClassNotFoundException {
		Plane u = new Plane();
		planes = u.viewData();
		Object title[] = { "飞机号", "航班号", "所属公司" };
		Object[][] detail = new Object[planes.size()][3];
		for (int i = 0; i < planes.size(); i++) {
			detail[i][0] = planes.get(i).getP_id();
			detail[i][1] = planes.get(i).getF_id();
			detail[i][2] = planes.get(i).getP_comp();

		}
		this.jTable1.setModel(new DefaultTableModel(detail, title));
	}
	
	/** Creates new form PControl */
	public PControl() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u6dfb\u52a0");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel1.setText("\u98de\u673a\u7ba1\u7406");

		jButton3.setText("\u5220\u9664");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u66f4\u6539");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("\u8fd4\u56de");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 547, Short.MAX_VALUE)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(80, 80, 80)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																452,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton2)
																		.addGap(
																				34,
																				34,
																				34)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton3)
																										.addGap(
																												33,
																												33,
																												33)
																										.addComponent(
																												jButton4)
																										.addGap(
																												32,
																												32,
																												32)
																										.addComponent(
																												jButton5)))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 509,
				Short.MAX_VALUE).addGroup(
				layout.createSequentialGroup().addGap(40, 40, 40).addComponent(
						jLabel1).addGap(32, 32, 32).addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton3).addComponent(jButton4)
								.addComponent(jButton5).addComponent(jButton1)
								.addComponent(jButton2)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 355,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								24, 24, 24)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CompanyView cv = new CompanyView();
		cv.setVisible(true);
		this.dispose();
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		int row = jTable1.getSelectedRow();
		int column = jTable1.getSelectedColumn();
		if (row == -1 || column == 0)
			return;

		String getColumn = (String) jTable1.getValueAt(row, column);// 要改的指
		String p_id = planes.get(row).getP_id();
		String select = TITLES2.get(column);// 选中的列
		try {
			Client c = new Client();
			Plane p = c.UpdatePlane(select, p_id, getColumn);
		} catch (UnknownHostException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

		JOptionPane.showMessageDialog(null, "更改成功", "提示",
				JOptionPane.PLAIN_MESSAGE);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		int row = jTable1.getSelectedRow();
		String pid = planes.get(row).getP_id();

		try {
			Client c = new Client();
			Plane p = c.DeletePlane(pid);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

		JOptionPane.showMessageDialog(null, "删除成功", "提示",
				JOptionPane.PLAIN_MESSAGE);
		planes.remove(row);
		// 更新表格
		jTable1.validate();
		jTable1.updateUI();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		PCinsert pi = new PCinsert();
		pi.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PControl().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}